# Generated by Django 4.2.4 on 2023-08-23 23:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_user_date_joined_user_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(blank=True)),
                ('static_path', models.CharField(max_length=512)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_parent_gal_thumb', models.BooleanField(default=False)),
                ('custom_order', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PickedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserPCInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('favorite', models.BooleanField(default=False)),
                ('pc_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.pickedcollection')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserMediaInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('favorite', models.BooleanField(default=False)),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.media')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserGalleryInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('favorite', models.BooleanField(default=False)),
                ('gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.gallery')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gallery_set', models.ManyToManyField(to='playground.gallery')),
                ('media_set', models.ManyToManyField(to='playground.media')),
            ],
        ),
        migrations.AddField(
            model_name='pickedcollection',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.user'),
        ),
        migrations.CreateModel(
            name='MediaCollectionInteractionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('favorite', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('custom_order', models.IntegerField(unique=True)),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.media')),
                ('pc_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.pickedcollection')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='media_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.mediaformat'),
        ),
        migrations.AddField(
            model_name='media',
            name='parent_gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.user'),
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=8)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playground.mediaformat')),
            ],
        ),
    ]
